const globalMessages = {
    btn_text: {
        save_button_text: 'SAVE CHANGES',
        back_button_text: 'Go Back',
        cancel_button_text: 'Cancel',
    },
    login_form: {
        title: 'Sign in',
        email_label: 'Email Address',
        email_placeholder: 'Enter your email address',
        password_label: 'Password',
        password_placeholder: 'Enter your password',
        login_button_text: 'Log in',
        logout_confirm: 'Are you sure you want to logout?',
    },
    actionRight: {
        action_title: "User Action Rights",
        role_title: "User Role",
        confirm: "Are you sure you want to update role ?",
        user_wise_label: "User Wise",
        user_role_wise_label: "User Role Wise",
        select_role: "Select Role",
        select_user: "Select User",
        role_assignment: "User Role Assignment"
    },
    signup_form: {
        title: 'Sign up',
        firstname_label: 'First Name',
        firstname_placeholder: 'Enter your first name',
        lastname_label: 'Last Name',
        lastname_placeholder: 'Enter your last name',
        email_label: 'Email Address',
        email_placeholder: 'Enter your email address',
        password_label: 'Password',
        password_placeholder: 'Enter your password',
        signup_button_text: 'SIGN UP',
    },
    change_password_form: {
        title: 'Change Password',
        current_password_label: 'Current Password',
        current_password_placeholder: 'Enter your current password',
        new_password_label: 'New Password',
        new_password_placeholder: 'Enter your new password',
        confirm_password_label: 'Confirm Password',
        confirm_password_placeholder: 'Enter your confirm password',
        password_button_text: 'SAVE CHANGES',
        cancel_button_text: 'CANCEL',
    },
    forget_password_form: {
        title: 'Forgot Password?',
        email_label: 'Email Address',
        email_placeholder: 'Enter your email address',
        button_text: 'SEND RESET LINK',
    },
    category: {
        table: 'Category',
        title: 'Category',
        search: 'Search Category',
        select_status: 'Select Status',
        name_label: 'Category Name',
        short_description_label: 'Short Description',
        select_label: 'Select Parent Category',
        long_description_label: 'Long Description',
        image_label: 'Category Image',
        is_active_label: 'Is Active',
        meta_title_label: 'Meta Title',
        meta_keyword_label: 'Meta Keyword',
        meta_description_label: 'Meta Description',
        save_button_text: 'Category',
        cancel_button_text: 'Cancel',
        delete_confirm: 'Do you want to delete this category?',
        update_confirm: 'Do you want to update the status of this category?',
    },
    client_group: {
        clientGroup: 'Client Group',
        type: 'ClientType',
        title: 'ClientGroup',
        search_label: 'Search Client Group',
        select_status: 'Select Status',
        name_label: 'Client Group Name',
        customer_type: 'Client Type',
        membership_from_date: ' Client Membership Start date date',
        membership_to_date: 'Client Membership End Date ',
        customer_signup_from_date: 'Customer Signup From Date',
        customer_signup_to_date: 'Customer Signup to Date',
        amount_paid_till_date: 'Amount paid till date',
        amount_outstanding_till_date: 'Outstanding amount till date',
        number_of_orders: 'number of orders',
        last_order_date: 'Last order date of',
        number_of_orders_in_last: 'No of order in days  ',
        product_id: 'select product',
        life_cycle_id: 'select lifecycle ',
        contact_type: 'select contect type',
        blocked_situation: 'select blocked situation',
        activity_type: 'select activity type',
        platform_id: 'select platform',
        category_id: 'select category',

    },
    promotion_form: {
        promocode_name: 'Promotion code ',
        description: 'Description',
        start_date: 'Start Date',
        end_date: 'End Date ',
        promotional_type: 'Selcet Promotion Types',
        promotional_for: 'Select Promotion Code For ',
        discount_type: 'Select Discount Type',
        discount_value: 'Discount value',
        customer_id: 'Customer',
        Customer_group_id: 'Customer Group Id',
        apply_to_product: 'Product Name ',
        select_product: 'Selcet Product',
        product_id: 'Product id',
        is_Active: 'Is Active',
        save_button_text: 'Promotional Code',

    },
    emailmarketing_form: {
        email: 'Email Template',
        title: 'Title',
        subject: 'Subject Of Email',
        message: 'Email Message',
        type_of_use: 'Type of Use',
        content_type: 'Content Type',
        attechment: 'File Upload',
        is_Active: 'Is Active',
        save_button_text: 'Template',

    },
    campaign: {
        campaign: 'Camapaign',
        title: 'Campaign Title',
        description: 'Description Of Campaign',
        from_name: 'Campaign From',
        From_email: 'Email Id Of Campaign Creator',
        template: 'Select Template Type',
        promotionalcode_For: 'Promotional Code For',
        promocode: 'Select Promotioonal Code',
        client_group_id: 'Select Client Group',
        campaign_date: 'Campaign Date',
        campaign_type: 'Campaign Type',
        is_active: 'Is Active',
        save_button_text: 'Campaign',
        cancel_button_text: 'Go back',
        bulk: 'BulK',
        oTo: 'One To One',

    },
    customer_testimonial: {
        testimonial: 'Customer Testimonial',
        description: 'Description Of Testimonial',
        name: 'Customer Name',
        email: 'Select Email',
        customer_company: 'Company Name',
        customer_designaition: 'Customer Designation',
        rating: '',
        image: '',
        is_active: 'Is Active',
        save_button_text: 'testimonial',
        cancel_button_text: 'Go back',

    },
    feedback: {
        feedback: 'Customer Feedback',
        feedbackfor: "Feedback For",
        rating: '',
        comment: 'Comment',
        save_button_text: 'feedback',
        cancel_button_text: 'Go back',

    },
    product: {
        table: 'Product',
        title: 'Product',
        search: 'Search Product',
        select_status: 'Select Status',
        name_label: 'Product Name',
        alias_label: 'Alias Name',
        qty_apply: 'Quantity Apply',
        price_label: 'Product Price',
        member_price_label: 'Product Member Price',
        sales_price_label: 'Product Sales Price',
        type_placeholder: 'Select Product Type',
        category_placeholder: 'Select Category',
        short_description_label: 'Short Description',
        long_description_label: 'Long Description',
        icon_label: 'Product Icon',
        image_label: 'Product Image',
        is_active_label: 'Is Active',
        meta_title_label: 'Meta Title',
        meta_keyword_label: 'Meta Keyword',
        meta_description_label: 'Meta Description',
        save_button_text: 'Product',
        cancel_button_text: 'Cancel',
        delete_confirm: 'Do you want to delete this product?',
        update_confirm: 'Do you want to update the status of this product?',
    },
    email_notification: {
        table: 'Email Notification Template',
        title: 'Email Notification Template',
        select_status: 'Select Status',
        search: 'Search Email Template',
        template_title_label: 'Template Title',
        primary_template_label: 'Select Primary Template',
        from_email_label: 'From Email',
        from_name_label: 'From Name',
        reply_email_label: 'Reply Email',
        reply_name_label: 'Reply Name',
        is_active_label: 'Is Active',
        send_admin_email: 'Send Mail To Admin',
        admin_email_type_label: 'Admin Email Type',
        admin_subject_label: 'Admin Subject',
        admin_body_label: 'Admin Description',
        send_team_email: 'Send Mail To Team',
        team_email_type_label: 'Admin Team Type',
        team_subject_label: 'Team Subject',
        team_body_label: 'Team Description',
        supervisor_email_type_label: 'Supervisor Email Type',
        send_supervisor_email: 'Send Mail To Supervisor',
        supervisor_subject_label: 'Supervisor Subject',
        supervisor_body_label: 'Supervisor Description',
        bde_email_type_label: 'BDE Email Type',
        send_bde_email: 'Send Mail To BD',
        bde_subject_label: 'BD Subject',
        bde_body_label: 'BD Description',
        pm_email_type_label: 'PM Email Type',
        send_pm_email: 'Send Mail To PM',
        pm_subject_label: 'PM Subject',
        pm_body_label: 'PM Description',
        customer_email_type_label: 'Customer Email Type',
        send_customer_label: 'Send Mail To Customer',
        customer_subject_label: 'Customer Subject',
        customer_body_label: 'Customer Description',
        save_button_text: 'Email Notification',
        cancel_button_text: 'Cancel',
        delete_confirm: 'Do you want to delete this email notification?',
        update_confirm: 'Do you want to update the status of this email notification?',
    },
    myprofile_form: {
        title: 'My Profile Details',
        firstname_label: 'First Name',
        firstname_placeholder: 'Enter your first name',
        lastname_label: 'Last Name',
        lastname_placeholder: 'Enter your last name',
        email_label: 'Email Address',
        email_placeholder: 'Enter your email address',
        phone_label: 'Phone Number',
        phone_placeholder: 'xxx xxx xxxx',
        country_label: 'Country',
        country_placeholder: 'Enter your country',
        state_label: 'State',
        state_placeholder: 'Enter your state',
        city_label: 'City',
        city_placeholder: 'Enter your city',
        save_button_text: 'SAVE CHANGES',
        cancel_button_text: 'CANCEL',
    },
    add_contact: {
        title_personal: 'Personal',
        field_title: 'Title',
        checkbox1: "Primary",
        checkbox2: "Is Active",
        contact_name: 'Contact name',
        contact_email: 'Contact Email',
        position: 'Position',
        qualification: 'Qualification',
        skills: 'skills',
        experience: 'Experience',
        birth_Date: 'Birth Date',
        anniversary_date: 'Anniversary Date',
        file: "Profile Pic",
        web_site: 'Web Site',
        title_contact_details: 'Contact Details',
        address1: 'Address1',
        address2: 'Address 2',
        city: 'City',
        state: 'State',
        country: 'Country',
        zip: 'Zip',
        phone: 'Phone',
        mobile: 'Mobile',
        longitude: 'Longitude',
        latitude: 'Latitude',
        timezone: 'Time Zone',
        imtype: 'IM Type',
        imid: 'IM ID',
    },
    add_preferences: {
        title_preferences: 'Preferences',
        bde: 'BDE',
        life_cycle_stage: 'Repeat',
        title_billing: 'Billing',
        billing_type: 'invoice',
        billing_days: '30',
        credit_limit: '$5000',
        currency: 'USD',
        business_type: 'B2B',
        title_email_preferences_for_qeHtml: 'Email Preferences for QeHtml',
        checkbox1: "Job Accept Decline Email",
        checkbox2: "Order Accepted BDE-PM",
        checkbox3: "Order Sign Off",
        checkbox4: "Lead Thread",
        checkbox5: "Sales Email",
        checkbox6: "Should cart be Emptied after 21 days?",
        checkbox7: "Job Mockup File Upload",
        checkbox8: "Order Status To Delivered",
        checkbox9: "Membership Next Payment",
        checkbox10: "Newsletter Email",
        checkbox11: "Anniversary Email",
        checkbox12: "Should Customer be Reminded for Cart Expiry?",
        checkbox13: "Order Placed Without Payment",
        checkbox14: "Order Next Payment",
        checkbox15: "Order Thread",
        checkbox16: "Promotional Email",
        checkbox17: " Seven Days to Registration",
        checkbox18: "Invoice Email",
    },
    add_customerbusinesses: {

        title_customer_website: 'Add Customer Website',
        web_site_url: "web Site Url",
        platform: "platform",
        founded_year: "Founded Year",
        website_domain_expiry_date: "website Domain Expiry Date",
        team_size: "Team Size",
        business_turnover: "Business Turn Over",
        primary_industry: "Primary Industry",
        website_design_score: "WebSite Design Score",
        seo_score: "SEO Score",
        no_of_pages_in_website: "No of Pages In Website",
        title_working_detail: 'Working Details',
        checkbox1: "Web Site Working",
        checkbox2: "Has Robots Txt",
        checkbox3: "Web Site Responsive",
        checkbox4: "SEO Score",
        checked_date: "Checked on Date"

    },

    add_attachment: {
        title: 'Add Attachments',
        add_file: "Add New File",
        remark_label: 'Remark',
    },
    arcticgrey: {
        title: "Arcticgrey",
        username: "User Name",
        password: "Password",
        website: "Web site",
        coutry: "Country",
        joined: "Joined",
        alternate_email: "Alternate Email"

    },
    user: {
        select_status: 'Select Status',
        table: "User",
        search: "Search User",
        select_role: 'User Role',
        from_date: 'From',
        to_date: 'To',
        form_title: "User",
        email: "Email",
        address1: "Address1",
        address2: "Address2",
        state: "State",
        country: "Country",
        city: "City",
        zip: "Zip",
        im_id: "IM ID",
        im_type: "IM type",
        twitter: "Twitter",
        anniversary: "Anniversary",
        user_name: "User Name",
        name: "Name",
        joining_date: "Joining Date",
        title: "Title",
        phone: "Phone",
        mobile: "Mobile",
        linkedin: 'Linkedin',
        facebook: 'Facebook',
        blog: 'Blog',
        qualification: 'Qualification',
        experience: 'Experience',
        skills: 'Skills',
        birth_date: 'Birth Date',
        save_button_text: 'User',
        delete_confirm: 'Do you want to delete users?',
        update_confirm: 'Do you want to update the status of this user?',
    },
    profile: {
        login_name: "Login Name",
        email: "Email",
        name: "Name",
        title: "Title",
        address1: "Address1",
        address2: "Address2",
        city: "City",
        state: "State",
        country: "Country",
        zip: "Zip",
        im_type: "IM Type",
        im_id: "IM ID",
        linked_in: "Linked In",
        facebook: "FaceBook",
        twitter: "Twitter",
        blog: "Blog",
        birthdate: "Birth Date",
        anniversary: "Anniversary",
        qualification: "Qualification",
        experience: "Experience"
    },
    source: {
        title: "Source",
        data_source: "Data Source",
        marketing_activity: "Marketing Activity",
    },
    block: {
        title: "Block",
        blocked_area_customer: "Blocked Area Customer",
        customer_blocked: "Customer Blocked"
    },
    billing: {
        title: "Billing",
        address: "Address",
        city: "City",
        zip: "Zip",
        state: "State",
        country: "Country",
        timezone: "Time Zone",
        phone: "Phone",
        mobile: "Mobile",
        email: "Email",
    },
    history: {
        title: "History",
        created_by: "Created By",
        created_date: "Created Date",
    },
    ip_tracking: {
        title: "IP Tracking",
        os: "Os ",
        address: "Address",
        country: "Country",
        region: "Region",
        city: "City",
        postal_code: "Postal Code"
    },
    misc: {
        title: "Misc",
        oauth_provider: "O Auth Provider ",
    },
    download_csv: {
        categories: "Categories",
        products: "Products",
        email_notification: "Email-Notification",
        cms: "CMS Pages",
        work_type: "Work Types",
        Project_template: "Project Templates",
        customer_testimonial: 'Customer Testimonials',
        Promotion: "Promotion Codes",
        my_orders: "My Orders"
    },
    cms: {
        title: 'Page',
        table_name: 'Pages',
        search: 'Search Page',
        select_status: 'Select Status',
        delete_confirm: 'Are you sure, you want to delete page?',
        status_update_confirm: 'Are you sure, you want to update page active status',
        page_title: 'Page Title',
        page_url: 'Page URL',
        description: 'Page Description',
        is_active: 'Is Active',
        meta_title: 'Meta Title',
        meta_description: 'Meta Description',
        save_button_text: 'Page',
        cancel_button_text: 'Cancel',
    },
    order_status: {
        order_status: 'Order Status',
        name: 'Name Of Order Status',
        dislplay_label: 'Label of Order Status',
        short_form: 'Short Form ',
        is_active: 'Is Active',
        cancel_button_text: 'Go back',
        save_button_text: 'Order Status',
    },
    order_allocation: {
        title: 'Order Allocation Details'
    },
    work_type: {
        title: 'Work Type',
        table_name: 'Work Type',
        search: 'Search Work Type',
        select_status: 'Select Status',
        delete_confirm: 'Are you sure, you want to delete work type?',
        status_update_confirm: 'Are you sure, you want to update work type active status',
        name: 'Work Type',
        is_active: 'Is Active',
        save_button_text: 'Work Type',
        cancel_button_text: 'Cancel',
    },
    project_template: {
        title: 'Project Template',
        table_name: 'Project Template',
        search: 'Search Project Template',
        select_status: 'Select Status',
        select_work_type: 'Select Work Type',
        template_title: 'Project Template Title',
        work_package_id: 'Work Package ID',
        work_package_title: 'Work Package Title',
        work_package_time: 'Estimate Time',
        task_id: 'Task ID',
        task_title: 'Task Title',
        task_time: 'Task Estimate Time',
        add_wp: 'Add Work Package',
        copy_wp: 'Copy Work Package',
        delete_confirm: 'Are you sure, you want to delete project template?',
        status_update_confirm: 'Are you sure, you want to update project template active status',
        name: 'Project Template',
        is_active: 'Is Active',
        save_button_text: 'Project Template',
        cancel_button_text: 'Cancel',
    },

    orders: {
        my_orders: "My Orders"
    },

    toDo: {
        delete: "Do you want to delete this to Do Activity",
    }
};

export default globalMessages;
